eden:
    security:
        oauth2:
            authorization:
                server:
                    enabled: true
            resource:
                server:
                    enabled: true

eureka:
    client:
        enabled: true
        fetch-registry: true
        healthcheck:
            enabled: true
        register-with-eureka: true
    instance:
        appname: ${spring.application.name}
        health-check-url-path: ${server.context-path}${management.context-path}/health
        home-page-url-path: ${server.context-path}
        instanceId: ${spring.application.name}.${spring.application.instance-id:${random.value}}
        metadata-map:
            instanceId: ${eureka.instance.instanceId}
            management:
                context-path: ${server.context-path}${management.context-path}
            profile: ${spring.profiles.active}
            version: #project.version#
            zone: primary
        prefer-ip-address: true
        status-page-url-path: ${server.context-path}${management.context-path}/info

feign:
    hystrix:
        enabled: true

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000

management:
    context-path: /management

ribbon:
    eureka:
        enabled: true
    ReadTimeout: 5000
    ConnectTimeout: 5000

security:
    oauth2:
        resource:
            filter-order: 3

server:
    context-path:
    servlet:
        session:
            cookie:
                http-only: true

spring:
    application:
        name: #project.name#
    boot:
        admin:
            client:
                prefer-ip: true
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
            indent-output: true
        time-zone: GMT+8
    jmx:
        default-domain: ${spring.application.name}
    jpa:
        hibernate:
            ddl-auto: none
        naming:
            implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
            physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        open-in-view: false
        properties:
            hibernate:
                cache:
                    use_second_level_cache: false
                    use_query_cache: false
                    use_minimal_puts: true
                    hazelcast.instance_name: ${spring.application.name}
                    hazelcast.use_lite_member: true
                ejb:
                    entitymanager_factory_name: ${spring.application.name}
                id:
                    new_generator_mappings: true
                region:
                    factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
    mvc:
        favicon:
            enabled: false
    profiles:
        active: #spring.profiles.active#
        include: #spring.profiles.include#
    zipkin:
        locator:
            discovery:
                enabled: true
