eden:
    integration:
        logstash:
            enabled: false
        swagger:
            default-include-pattern: /(api|oauth|${management.context-path})/.*
            title: #project.description#
            version: #project.version#
    security:
        jwt:
            authentication:
                base64-secret: MjEyMzJmMjk3YTU3YTVhNzQzODk0YTBlNGE4MDFmYzMyMTIzMmYyOTdhNTdhNWE3NDM4OTRhMGU0YTgwMWZjMw==
            authorization:
                header: JwtAuthorization

eureka:
    client:
        instance-info-replication-interval-seconds: 10
        metadata:
            user:
                name: ${security.user.name}
                password: ${security.user.password}
        registry-fetch-interval-seconds: 10
        service-url:
            defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/,http://${security.user.name}:${security.user.password}@localhost:8762/eureka/
    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10

logging:
    file: target/${spring.application.name}.log
    level:
        ROOT: INFO
        org.ylzl.eden: DEBUG

security:
    user:
        name: admin
        password: 21232f297a57a5a743894a0e4a801fc3
        roles: ROLE_ADMIN

server:
    port: 8888

spring:
    zipkin:
        base-url: http://localhost:9411
        enabled: false
