eden:
    security:
        jwt:
            authorization:
                server:
                    enabled: true

eureka:
    client:
        enabled: true
        fetch-registry: true
        healthcheck:
            enabled: true
        register-with-eureka: true
    instance:
        appname: ${spring.application.name}
        health-check-url-path: ${server.context-path}${management.context-path}/health
        home-page-url-path: ${server.context-path}
        instanceId: ${spring.application.name}.${spring.application.instance-id:${random.value}}
        metadata-map:
            instanceId: ${eureka.instance.instanceId}
            management:
                context-path: ${server.context-path}${management.context-path}
            profile: ${spring.profiles.active}
            version: #project.version#
            zone: primary
        prefer-ip-address: true
        status-page-url-path: ${server.context-path}${management.context-path}/info

management:
    context-path: /management

security:
    oauth2:
        resource:
            filter-order: 3

server:
    context-path:
    servlet:
        session:
            cookie:
                http-only: true

spring:
    application:
        name: #project.name#
    boot:
        admin:
            client:
                prefer-ip: true
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
            indent-output: true
        time-zone: GMT+8
    jmx:
        default-domain: ${spring.application.name}
    mvc:
        favicon:
            enabled: false
    profiles:
        active: #spring.profiles.active#
        include: #spring.profiles.include#
    zipkin:
        locator:
            discovery:
                enabled: true
